### PR TITLE
IMP set adminer as plugin

### PR DESCRIPTION
**Pull request by bealdav**
Better adminer integration

### CODE REVIEW

**Comment by bealdav** [comment]
cc @metaminux

**Review by Kev-Roche — APPROVED** [review]

**Comment by bealdav** [comment]
cc @hparfr pas d'objection à un merge ?

**Comment by metaminux** [comment]
@bealdav Maybe you should rename **.adminer.dc.yml** to **{% if provide_adminer %}.adminer.dc.yml{% endif %}**

and add some labels for traefik (see .wdb.dc.yml) to ease access... currently, I don't understand exactly how you access the adminer container when started...

**Comment by bealdav** [comment]
Hi @metaminux thanks a lot for this review, I missed to rename file.
I copy paste your traefik settings and it's just works too.
I've tried in the past but failed.

**Comment by bealdav** [comment]
Easy to dive in adminer now

adm

Really thanks

**Comment by metaminux** [comment]
> Really thanks

You're welcome 😄 

Easier to access indeed !

**Review by metaminux — APPROVED** [review]

**Pull request merged**
