### PR TITLE
[FIX] report url for ci

### PR DESCRIPTION
**Pull request by florian-dacosta**
Not sure it is the best value ever, but at least it works fine this way.

@sebastienbeau @hparfr @PierrickBrun

### CODE REVIEW

**Comment by hparfr** [comment]
In ci, you may have multiple `odoo` and only one report server; may be there is a local absolute name we may use or use traefik routing for that.

**Review by hparfr — APPROVED** [review]

**Review by sebastienbeau — CHANGES_REQUESTED** [review]
Can we check your issue?

Normally 
```
ODOO_REPORT_URL: http://ci-${BUILD_NAME}:8069
```
should work because in the ".env-ci" you will have

```
ENV=ci
COMPOSE_PROJECT_NAME=${BUILD_NAME}
```

And so the container that run odoo will have as alias "ci-${BUILD_NAME}" in the local network.

So normally the kwhtmltopdf container should be able to contact odoo with this alias.

I just test it right now on a fresh project and it's work.

**Comment by florian-dacosta** [comment]
> should work because in the ".env-ci" you will have
> 
> ```
> ENV=ci
> COMPOSE_PROJECT_NAME=${BUILD_NAME}
> ```

Oh ! Nice to know, I think it deserves a comment, because it is not obvious to all.
The issue we ran in multiple project (me and David for now) is indeed because we did change the ENV in the .env-sample file.
The ENV also changes the running env of Odoo and, not everybody want an "CI environment".
For example, I rarely manage more than "prod" and "dev", because I rarely (never ?) have different accounts between ci/preprod and dev environment.

Can't it be changed by `http://${ENV}-${BUILD_NAME}:8069` then ?

**Comment by sebastienbeau** [comment]
indead http://${ENV}-${BUILD_NAME}:8069 seem to be the right solution

The alternative is to remove from the container name the ENV : https://github.com/akretion/docky-odoo-template/blob/e75156e31a1685effe25725540c833dc9fcae1e2/docker-compose.yml#L33

@hparfr what do you think ?

**Comment by florian-dacosta** [comment]
After the explanation of Sebastien, I have updated the report url to make it env dependent.
+ I make the kwkhtmltopdf container in restart always mode

**Comment by hparfr** [comment]
the env in the host name is important. 
It's too easy to trigger an action in the wrong env if you have multiple project / multiple env open at the same time.

**Comment by hparfr** [comment]
I don't get why this  `.env-sample` has been put here. It's a regression. Originally `copier` create and manage this file.

**Comment by florian-dacosta** [comment]
@sebastienbeau @hparfr Seems good now ?
I don't know about any `.env-sample` but it seems unrelated to this PR right ?

**Comment by bealdav** [comment]
I suppose we should debate of `.env-sample` in an issue if needed and merge this one if original topic is OK for all.

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
@sebastienbeau please adapt your review

**Review by sebastienbeau — APPROVED** [review]

**Pull request merged**
