### PR TITLE
IMP pre-commit run --all -> pre-commit run to allow use exclusion in pre-commit.yaml

### PR DESCRIPTION
**Pull request by bealdav**
In some case you have source code that you want keep as it because it's a copy paste from an external.
Then you may want add clause exclusion

### CODE REVIEW

**Comment by rvalyi** [comment]
in fact, there is no such `--all` option apparently. The one that is used in the OCA is `--all-files` and I suggest we use the same as the OCA. Then you can still mark particular directories or files to be excluded in the `.pre-commit-config.yaml` file. Here is an example: https://github.com/OCA/l10n-brazil/blob/14.0/.pre-commit-config.yaml#L5
What do you think?

**Comment by bealdav** [comment]
Ok, but I don't found `--all-files` in `oca-addons-repo-template`

**Comment by rvalyi** [comment]
> oca-addons-repo-template

it's here https://github.com/OCA/oca-addons-repo-template/blob/master/src/.github/workflows/pre-commit.yml.jinja#L41
example: https://github.com/OCA/account-invoicing/blob/16.0/.github/workflows/pre-commit.yml#L27

**Comment by bealdav** [comment]
In fact I'm not sure to execute my exclusion correctly. Maybe a misunderstood of my part.
But to be aligned to OCA ? Probably yes

**Comment by sebastienbeau** [comment]
Hi, the --all or --all-files is the same things (but it would be cleaner to use --all-files)

It will run the pre-commit on all the files of the project (it respect the exclusion, so a file excluded is not tested with the option --all-files)

**Comment by bealdav** [comment]
in fact I had a misunderstood if exceptions config because I forgot the `|` for each exception line, then my exception was not taken in account

**Comment by bealdav** [comment]
Can be close

**Pull request closed without merging**
