### PR TITLE
[ADD] enable web debugger in docker

### PR DESCRIPTION
**Pull request by metaminux**
@Kev-Roche here is the addition for a web debugger.

I made it "pluggable" for the main part, there is just the addition to the dev image in Dockerfile that is not.

Documentation for WDB usage is here : https://github.com/Kozea/wdb#readme

Feel free to comment.

### CODE REVIEW

**Comment by Kev-Roche** [comment]
Thank you @metaminux , from my point of view, it s a nice and improved alternative of the classic pdb.

**Comment by kevinkhao** [comment]
thank you @metaminux 
seems interesting, as far as usage do you typically just put a import wdb; wdb.set_trace() ?
also 
> wdb works with python 2 (2.6, 2.7), python 3 (3.2, 3.3, 3.4, 3.5) and pypy
no issues ?

**Comment by metaminux** [comment]
@kevinkhao Yes I typically add
```python
import wdb
wdb.set_trace()
```
and I never had issues about the python version

**Comment by bealdav** [comment]
Nice addition, thanks.

Maybe we could ask for add it like here https://github.com/akretion/docky-odoo-template/blob/main/copier.yml#L28-L29 ?

**Comment by metaminux** [comment]
> Nice addition, thanks.
> 
> Maybe we could ask for add it like here https://github.com/akretion/docky-odoo-template/blob/main/copier.yml#L28-L29 ?

Hi @bealdav 

I suppose using copier answer would provide a better way to add it or not in the Dockerfile, is this what you have in mind ?

I just made it "pluggable" using the same logic that was already used for adminer, so that we just have to put / remove it in .env file

**Comment by metaminux** [comment]
@bealdav We're now asking for the addition of web debugger or not.

**Comment by bealdav** [comment]
Thanks a lot
I suggest to ask for a review to @hparfr
I suppose he has an opinion on the way to do it.
If everybody is OK, we may also manage adminer with the same way.

**Comment by hparfr** [comment]
@Kev-Roche @kevinkhao @bealdav have you tested this PR ? Then you can update your reviews.

PS: The author of wdb says it's not maintained  anymore and he has started a refactoring.

**Comment by bealdav** [comment]
I haven't tested, but I'm not sure this is really necessary for now.

We just need to ensure to this PR make a sort of plugin system, no ?

**Comment by bealdav** [comment]
When this PR 'll be merged I might switch adminer config in the way except if somebody think it's a bad idea.

**Comment by metaminux** [comment]
@Kev-Roche ? @kevinkhao ? @bealdav ? Anyone ? To get a review on that PR to unlock merging...

**Comment by Kev-Roche** [comment]
@hparfr , @bealdav , @kevinkhao 
LGTM
If no objection at the end of the week, I'll merge it.

**Review by Kev-Roche — APPROVED** [review]

**Review by bealdav — APPROVED** [review]

**Comment by hparfr** [comment]
So, @Kev-Roche did you test it ?

**Pull request merged**
